# Generated by Django 5.1.7 on 2025-03-26 13:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basvuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("Beklemede", "Beklemede"),
                            ("Onaylandı", "Onaylandı"),
                            ("Reddedildi", "Reddedildi"),
                        ],
                        default="Beklemede",
                        max_length=20,
                    ),
                ),
                ("basvuru_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=255)),
                ("aciklama", models.TextField()),
                (
                    "kadro",
                    models.CharField(
                        choices=[
                            ("Dr. Öğr. Üyesi", "Dr. Öğr. Üyesi"),
                            ("Doçent", "Doçent"),
                            ("Profesör", "Profesör"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gereksinimler", models.TextField()),
                ("baslangic_tarihi", models.DateField()),
                ("bitis_tarihi", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="KadroKriterleri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kriter_adi", models.CharField(max_length=255)),
                ("kriter_detaylari", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Belge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belge_turu",
                    models.CharField(
                        choices=[
                            ("Atıf Sayısı", "Atıf Sayısı"),
                            ("Konferans Yayını", "Konferans Yayını"),
                            ("Diğer", "Diğer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dosya_yolu", models.CharField(max_length=255)),
                ("yuklenme_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "basvuru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basvuru.basvuru",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basvuru",
            name="ilan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="basvuru.ilan"
            ),
        ),
        migrations.CreateModel(
            name="Kullanici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("tc_kimlik", models.CharField(max_length=11, unique=True)),
                ("ad", models.CharField(max_length=100)),
                ("soyad", models.CharField(max_length=100)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Aday", "Aday"),
                            ("Admin", "Admin"),
                            ("Yönetici", "Yönetici"),
                            ("Jüri Üyesi", "Jüri Üyesi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="kullanici_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="kullanici_set", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="JuriDegerlendirme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "karar",
                    models.CharField(
                        choices=[("Olumlu", "Olumlu"), ("Olumsuz", "Olumsuz")],
                        max_length=20,
                    ),
                ),
                ("degerlendirme_metni", models.TextField()),
                ("degerlendirme_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "basvuru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basvuru.basvuru",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basvuru.kullanici",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ilan",
            name="olusturan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basvuru.kullanici",
            ),
        ),
        migrations.CreateModel(
            name="Bildirim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mesaj", models.TextField()),
                ("gonderim_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basvuru.kullanici",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basvuru",
            name="kullanici",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="basvuru.kullanici"
            ),
        ),
    ]
